version: '3'
services:
  web:
    build: .
    expose:
      - "50006"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
    command: certonly --standalone --noninteractive --agree-tos --email ${CERTBOT_EMAIL} -d timestamp.lugenx.com
    restart: always

volumes:
  certs:
